// Auto-generated by `node server/server.mjs --build` — do not edit by hand.
// Body for: 2025-09-01/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2025-09-01/index.md"] = "# Problem\n\nI've always wanted to create an interactive tool to visualize what's happening within a neural network.\n\n# Solution\n\nAnd so I did:\n\n- [visualizing-neural-networks.marcuschiu.com](https://visualizing-neural-networks.marcuschiu.com)\n\n[![alt](articles/2025-09-01/assets/1.jpeg)](https://visualizing-neural-networks.marcuschiu.com)\n";
