// Auto-generated by `node server/server.mjs --build` — do not edit by hand.
// Body for: 2025-06-14/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2025-06-14/index.md"] = "- **permutation** - refers to the different ways of arranging items from a set of objects, in a sequential order \n- **combination** - refers to the different ways of choosing items from a set of objects, such that their order does not matter\n\n[![alt](articles/2025-06-14/assets/1.jpeg)](assets/1.jpeg)\n\n# Totality\n\n[![alt](articles/2025-06-14/assets/2.jpeg)](assets/2.jpeg)\n";
