// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.
// Body for: 2025-08-14/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2025-08-14/index.md"] = "I've first made tetris using [`<canvas>`](/tinkering/2025-08-07/)\nthen also in [Unicode](/tinkering/2025-08-11/) (i.e. 🟧🟪🟥🟦🟨🟩).\n\nSo late at night, I've decided to make tetris again using ASCII characters.\n\n[tetris-ascii.marcuschiu.com](https://tetris-ascii.marcuschiu.com)\n\n[![alt](articles/2025-08-14/assets/1.jpeg)](https://tetris-ascii.marcuschiu.com)\n";
