// Auto-generated by `node server/server.mjs --build` — do not edit by hand.
// Body for: 2025-08-18/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2025-08-18/index.md"] = "# Problem\n\nI wanna recreate Shazam :(\n\n# Solution\n\nAnd so I did. Here it is :D\n\n- [shazam.marcuschiu.com](https://shazam.marcuschiu.com)\n\n[![alt](articles/2025-08-18/assets/1.jpeg)](https://shazam.marcuschiu.com)\n\n\n\n";
