// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.
window.ARTICLES = [
  {
    "slug": "2026-06-11--TEST-ARTICLE",
    "path": "2026-06-11/index.md",
    "title": "TEST ARTICLE",
    "date": "2026-06-11",
    "tags": [
      "combinatorics",
      "test"
    ],
    "img": "2026-06-11/assets/Snap_Camera_Photo_2.jpg"
  },
  {
    "slug": "2026-03-12--OPNSense-Firewal-DNS-Redirection",
    "path": "2026-03-12/index.md",
    "title": "OPNSense Firewal DNS Redirection",
    "date": "2026-03-12",
    "tags": [
      "opnsense",
      "networking",
      "dns",
      "firewall",
      "router"
    ],
    "img": "2026-03-12/assets/cover.png"
  },
  {
    "slug": "2026-01-31--Disable-SSH-Password-Login-in-Proxmox-LXC-Containers",
    "path": "2026-01-31/index.md",
    "title": "Disable SSH Password Login in Proxmox LXC Containers",
    "date": "2026-01-31",
    "tags": [
      "homelab",
      "proxmox",
      "ssh",
      "security",
      "lxc"
    ],
    "img": "2026-01-31/assets/cover.png"
  },
  {
    "slug": "2026-01-30--How-to-Uninstall-Fedora-Asahi-Linux-from-an-M1-MacBook-Pro",
    "path": "2026-01-30/index.md",
    "title": "How to Uninstall Fedora Asahi Linux from an M1 MacBook Pro",
    "date": "2026-01-30",
    "tags": [
      "macos",
      "linux",
      "apple-silicon"
    ],
    "img": "2026-01-30/assets/cover.png"
  },
  {
    "slug": "2026-01-29--Adding-Firewall-to-Proxmox-LXC-Containers",
    "path": "2026-01-29/index.md",
    "title": "Adding Firewall to Proxmox LXC Containers",
    "date": "2026-01-29",
    "tags": [
      "homelab",
      "proxmox",
      "firewall",
      "security",
      "lxc"
    ],
    "img": "2026-01-29/assets/cover.png"
  },
  {
    "slug": "2026-01-28--Creating-a-Discord-AI-Agent-with-n8n",
    "path": "2026-01-28/index.md",
    "title": "Creating a Discord AI Agent with n8n",
    "date": "2026-01-28",
    "tags": [
      "ai",
      "n8n",
      "discord",
      "automation",
      "chatbot"
    ],
    "img": "2026-01-28/assets/cover.png"
  },
  {
    "slug": "2026-01-26--Simulating-100%2C000-Celestial-Bodies",
    "path": "2026-01-26/index.md",
    "title": "Simulating 100,000 Celestial Bodies",
    "date": "2026-01-26",
    "tags": [
      "algorithms",
      "simulation",
      "physics",
      "web-development"
    ],
    "img": "2026-01-26/assets/cover.png"
  },
  {
    "slug": "2026-01-24--Coding-AI-Coding-Agent",
    "path": "2026-01-24/index.md",
    "title": "Coding AI Coding Agent",
    "date": "2026-01-24",
    "tags": [
      "ai",
      "llm",
      "claude",
      "python",
      "agents"
    ],
    "img": "2026-01-24/assets/cover.png"
  },
  {
    "slug": "2025-12-03--How-to-Setup-a-Bitcoin-Pruned-Node-Over-TOR-on-Ubuntu",
    "path": "2025-12-03/index.md",
    "title": "How to Setup a Bitcoin Pruned Node Over TOR on Ubuntu",
    "date": "2025-12-03",
    "tags": [
      "bitcoin",
      "tor",
      "linux",
      "self-hosting",
      "privacy"
    ],
    "img": "2025-12-03/assets/cover.png"
  },
  {
    "slug": "2025-12-02--NFS-Client-on-Proxmox-LXC",
    "path": "2025-12-02/index.md",
    "title": "NFS Client on Proxmox LXC",
    "date": "2025-12-02",
    "tags": [
      "homelab",
      "proxmox",
      "nfs",
      "lxc",
      "storage"
    ],
    "img": "2025-12-02/assets/cover.png"
  },
  {
    "slug": "2025-12-01--How-to-Enable-IOMMU-on-ASROCK-ROMED8-2T",
    "path": "2025-12-01/index.md",
    "title": "How to Enable IOMMU on ASROCK ROMED8-2T",
    "date": "2025-12-01",
    "tags": [
      "homelab",
      "hardware",
      "bios",
      "virtualization"
    ],
    "img": "2025-12-01/assets/cover.png"
  },
  {
    "slug": "2025-09-18--I've-3D-Scanned-my-Room-(3D-Gaussian-Splatting)",
    "path": "2025-09-18/index.md",
    "title": "I've 3D Scanned my Room (3D Gaussian Splatting)",
    "date": "2025-09-18",
    "tags": [
      "3d-reconstruction",
      "gaussian-splatting",
      "computer-vision"
    ],
    "img": "2025-09-18/assets/cover.png"
  },
  {
    "slug": "2025-09-17--Markov-Chain-Monte-Carlo-(MCMC)",
    "path": "2025-09-17/index.md",
    "title": "Markov Chain Monte Carlo (MCMC)",
    "date": "2025-09-17",
    "tags": [
      "mathematics",
      "statistics",
      "mcmc",
      "algorithms"
    ],
    "img": "2025-09-17/assets/cover.png"
  },
  {
    "slug": "2025-09-01--Vizualizing-Neural-Networks-(Interactive-Tool)",
    "path": "2025-09-01/index.md",
    "title": "Vizualizing Neural Networks (Interactive Tool)",
    "date": "2025-09-01",
    "tags": [
      "machine-learning",
      "neural-networks",
      "visualization",
      "web-development"
    ],
    "img": "2025-09-01/assets/cover.png"
  },
  {
    "slug": "2025-08-21--Shazam-Theory-%231---FT-DTFT-DFT-FFT-STFT",
    "path": "2025-08-21/index.md",
    "title": "Shazam Theory #1 - FT DTFT DFT FFT STFT",
    "date": "2025-08-21",
    "tags": [
      "signal-processing",
      "fourier-transform",
      "mathematics",
      "audio"
    ],
    "img": "2025-08-21/assets/cover.jpeg"
  },
  {
    "slug": "2025-08-18--I've-Recreated-Shazaam",
    "path": "2025-08-18/index.md",
    "title": "I've Recreated Shazaam",
    "date": "2025-08-18",
    "tags": [
      "signal-processing",
      "audio",
      "web-development"
    ],
    "img": "2025-08-18/assets/cover.png"
  },
  {
    "slug": "2025-08-17--Promox-Gitea---Change-HTTP-Port-to-80",
    "path": "2025-08-17/index.md",
    "title": "Promox Gitea - Change HTTP Port to 80",
    "date": "2025-08-17",
    "tags": [
      "homelab",
      "proxmox",
      "gitea",
      "self-hosting"
    ],
    "img": "2025-08-17/assets/cover.png"
  },
  {
    "slug": "2025-08-16--Alert-Me-on-Disk-Full--(Telegraf-%2B-InfluxDB-%2B-Grafana)",
    "path": "2025-08-16/index.md",
    "title": "Alert Me on Disk Full  (Telegraf + InfluxDB + Grafana)",
    "date": "2025-08-16",
    "tags": [
      "homelab",
      "monitoring",
      "grafana",
      "influxdb",
      "telegraf"
    ],
    "img": "2025-08-16/assets/cover.png"
  },
  {
    "slug": "2025-08-15--The-Law-of-First-Mention",
    "path": "2025-08-15/index.md",
    "title": "The Law of First Mention",
    "date": "2025-08-15",
    "tags": [
      "bible",
      "web-development",
      "javascript"
    ],
    "img": "2025-08-15/assets/cover.png"
  },
  {
    "slug": "2025-08-14--I've-Built-Tetris-Using-ASCII",
    "path": "2025-08-14/index.md",
    "title": "I've Built Tetris Using ASCII",
    "date": "2025-08-14",
    "tags": [
      "javascript",
      "game-development",
      "web-development"
    ],
    "img": "2025-08-14/assets/cover.png"
  },
  {
    "slug": "2025-08-13--Alert-me-on-High-Temps-(Telegraf-%2B-InfluxDB-%2B-Grafana)",
    "path": "2025-08-13/index.md",
    "title": "Alert me on High Temps (Telegraf + InfluxDB + Grafana)",
    "date": "2025-08-13",
    "tags": [
      "homelab",
      "monitoring",
      "grafana",
      "influxdb",
      "telegraf"
    ],
    "img": "2025-08-13/assets/cover.png"
  },
  {
    "slug": "2025-08-11--I've-Built-Tetris-Using-Unicode",
    "path": "2025-08-11/index.md",
    "title": "I've Built Tetris Using Unicode",
    "date": "2025-08-11",
    "tags": [
      "javascript",
      "game-development",
      "web-development"
    ],
    "img": "2025-08-11/assets/cover.png"
  },
  {
    "slug": "2025-08-08--Locked-out-of-my-Router-(OPNsense)",
    "path": "2025-08-08/index.md",
    "title": "Locked out of my Router (OPNsense)",
    "date": "2025-08-08",
    "tags": [
      "opnsense",
      "networking",
      "troubleshooting",
      "router"
    ],
    "img": "2025-08-08/assets/cover.png"
  },
  {
    "slug": "2025-08-07--I've-Built-Tetris-Using-ReactJS",
    "path": "2025-08-07/index.md",
    "title": "I've Built Tetris Using ReactJS",
    "date": "2025-08-07",
    "tags": [
      "react",
      "javascript",
      "game-development",
      "web-development"
    ],
    "img": "2025-08-07/assets/cover.png"
  },
  {
    "slug": "2025-07-30--Spring-Boot-3.5-Guides",
    "path": "2025-07-30/index.md",
    "title": "Spring Boot 3.5 Guides",
    "date": "2025-07-30",
    "tags": [
      "spring-boot",
      "java",
      "backend",
      "programming"
    ],
    "img": "2025-07-30/assets/cover.png"
  },
  {
    "slug": "2025-07-16--Network-File-System-(NFS)",
    "path": "2025-07-16/index.md",
    "title": "Network File System (NFS)",
    "date": "2025-07-16",
    "tags": [
      "linux",
      "nfs",
      "networking",
      "storage"
    ],
    "img": "2025-07-16/assets/cover.png"
  },
  {
    "slug": "2025-06-21--Homelab-%238---Wake-on-LAN-(WoL)-Proxmox",
    "path": "2025-06-21/index.md",
    "title": "Homelab #8 - Wake on LAN (WoL) Proxmox",
    "date": "2025-06-21",
    "tags": [
      "homelab",
      "proxmox",
      "networking",
      "wake-on-lan"
    ],
    "img": "2025-06-21/assets/cover.png"
  },
  {
    "slug": "2025-06-14--Permutation-vs-Combination",
    "path": "2025-06-14/index.md",
    "title": "Permutation vs Combination",
    "date": "2025-06-14",
    "tags": [
      "mathematics",
      "combinatorics"
    ],
    "img": "2025-06-14/assets/cover.png"
  },
  {
    "slug": "2025-06-13--How-to-Install-qBittorrent-on-Ubuntu-Server-24.04",
    "path": "2025-06-13/index.md",
    "title": "How to Install qBittorrent on Ubuntu Server 24.04",
    "date": "2025-06-13",
    "tags": [
      "linux",
      "ubuntu",
      "systemd",
      "self-hosting"
    ],
    "img": "2025-06-13/assets/cover.png"
  },
  {
    "slug": "2025-06-12--Making-This-Website-HTTPS",
    "path": "2025-06-12/index.md",
    "title": "Making This Website HTTPS",
    "date": "2025-06-12",
    "tags": [
      "ssl",
      "nginx",
      "lets-encrypt",
      "security",
      "web-development"
    ],
    "img": "2025-06-12/assets/cover.png"
  },
  {
    "slug": "2025-06-11--Homelab-%237---Kasm",
    "path": "2025-06-11/index.md",
    "title": "Homelab #7 - Kasm",
    "date": "2025-06-11",
    "tags": [
      "homelab",
      "kasm",
      "remote-desktop",
      "self-hosting"
    ],
    "img": "2025-06-11/assets/cover.png"
  },
  {
    "slug": "2025-06-10--Homelab-%236---Fixing-Homebox-Perpetual-Logouts",
    "path": "2025-06-10/index.md",
    "title": "Homelab #6 - Fixing Homebox Perpetual Logouts",
    "date": "2025-06-10",
    "tags": [
      "homelab",
      "kubernetes",
      "nginx",
      "troubleshooting"
    ],
    "img": "2025-06-10/assets/cover.png"
  },
  {
    "slug": "2025-06-08--Homelab-%235---Kubernetes-Cluster-(App-Bonanza!!!!!!)",
    "path": "2025-06-08/index.md",
    "title": "Homelab #5 - Kubernetes Cluster (App Bonanza!!!!!!)",
    "date": "2025-06-08",
    "tags": [
      "homelab",
      "kubernetes",
      "self-hosting",
      "containers"
    ],
    "img": "2025-06-08/assets/cover.png"
  },
  {
    "slug": "2025-06-06--Homelab-%234---Kubernetes-Cluster-(Infrastructure-Setup)",
    "path": "2025-06-06/index.md",
    "title": "Homelab #4 - Kubernetes Cluster (Infrastructure Setup)",
    "date": "2025-06-06",
    "tags": [
      "homelab",
      "kubernetes",
      "helm",
      "networking",
      "storage"
    ],
    "img": "2025-06-06/assets/cover.png"
  },
  {
    "slug": "2025-06-05--Homelab-%233---Kubernetes-Cluster-(Initial-Setup)",
    "path": "2025-06-05/index.md",
    "title": "Homelab #3 - Kubernetes Cluster (Initial Setup)",
    "date": "2025-06-05",
    "tags": [
      "homelab",
      "kubernetes",
      "proxmox",
      "containers"
    ],
    "img": "2025-06-05/assets/cover.png"
  },
  {
    "slug": "2025-06-04--Homelab-%232---Proxmox-Cluster",
    "path": "2025-06-04/index.md",
    "title": "Homelab #2 - Proxmox Cluster",
    "date": "2025-06-04",
    "tags": [
      "homelab",
      "proxmox",
      "virtualization",
      "clustering"
    ],
    "img": "2025-06-04/assets/cover.jpg"
  },
  {
    "slug": "2025-06-03--Creating-This-Website",
    "path": "2025-06-03/index.md",
    "title": "Creating This Website",
    "date": "2025-06-03",
    "tags": [
      "web-development",
      "hugo",
      "static-site"
    ],
    "img": "2025-06-03/assets/cover.jpeg"
  },
  {
    "slug": "2024-08-26--Homelab-%231---Humble-Beginnings",
    "path": "2024-08-26/index.md",
    "title": "Homelab #1 - Humble Beginnings",
    "date": "2024-08-26",
    "tags": [
      "homelab",
      "hardware",
      "networking",
      "server-rack"
    ],
    "img": "2024-08-26/assets/cover.jpeg"
  }
];
